app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/**
Route::get('/', function () {
    return view('welcome');
});
*/
Route::get('/', ['middleware' => 'auth', function () {
    return view('home');
}]);

/*
Route::get('/nueva-apuesta', ['middleware' => 'auth', function () {
    return view('nuevaapuesta');
    
}]);
*/

/* 	con el siguiente comando se crea el controlador con dotos sus medotos para el tipico CRUD
	php artisan make:controller Apuesta
	Podemos revizar en la capeta ontroller 
	tambien podemos ver todas las rutas quie tiene hasta el momento nuestra aplicacion con:
	php artisan route:list
	hasta el momento no esta la rutas para el nuevo controlador, con locando la siguuente linea en
	el archivo de route.php
	Route::resource('apuesta', 'Apuesta');
	apuesta -> Nombre de la ruta
	Apuesta -> Nombre del controlador
	ahora si vemos otravez las ruta ya estan las nuevas.
	php artisan route:list

	Alternativa Route::resource('apuesta', 'Apuesta', ['only' => [
	    'index', 'show'
	]]);

	Route::resource('apuesta', 'Apuesta', ['except' => [
	    'create', 'store', 'update', 'destroy'
	]]);
*/


Route::resource('apuesta', 'Apuesta');
Route::resource('apostadores', 'Apostadores');

resources/views/app.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>

@include('partials.htmlheader')

<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="skin-blue sidebar-mini">
<div class="wrapper">

    @include('partials.mainheader')

    @include('partials.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @include('partials.contentheader')

        <!-- Main content -->
        <section class="content">
            <!-- Your Page Content Here -->
            @yield('main-content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    @include('partials.controlsidebar')

    @include('partials.footer')

</div><!-- ./wrapper -->

@include('partials.scripts')

</body>
</html>

resources/views/compartir.blade.php
<div class="box-body">
	<div class="col-lg-12">
		<div class="box-body table-responsive no-padding">
			<table class="table table-hover" id="tabla_apostadores">
				<thead>
					<tr>
						<th>Nombre Apostador</th>
						<th colspan="2">Marcador</th>
						<th colspan="2">Operaciones</th>
					</tr>
				</thead>
				<tbody>
					
					 @foreach ($apuesta as $apostador)
					 @endforeach
				</tbody>
			</table>
		</div>
	</div>
</div

resources/views/home.blade.php
@extends('app')

@section('htmlheader_title')
    Patrocinadores
@endsection

@section('contentheader_title')
    Patrocinadores
@endsection


@section('main-content')
	<div class="row">
		<div class="col-md-5 col-md-offset-1">
			<div class="panel panel-primary">
				<div class="panel-heading">La Fotocopias más Veloz</div>

				<div class="panel-body">
					<img src="{{asset('/img/fotocopia.jpeg')}}" class="img-responsive img-thumbnail">
				</div>
			</div>
		</div>
		<div class="col-md-5">
			<div class="panel panel-primary">
				<div class="panel-heading">La Mejor Hamburguesas de la U</div>

				<div class="panel-body">
				<img src="{{asset('/img/cofeteria.jpeg')}}" class="img-responsive img-thumbnail">
				</div>
			</div>
		</div>
	</div><div class="row">
		<div class="col-md-5 col-md-offset-1">
			<div class="panel panel-primary">
				<div class="panel-heading">Desayuna sano y Saludable</div>

				<div class="panel-body">
					<img src="{{asset('/img/cereal.jpeg')}}" class="img-responsive img-thumbnail">
				</div>
			</div>
		</div>
		<div class="col-md-5">
			<div class="panel panel-primary">
				<div class="panel-heading">Lo mejor despues de un Duro Parcial</div>

				<div class="panel-body">
				<img src="{{asset('/img/girasoles.jpeg')}}" class="img-responsive img-thumbnail">
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/misapuestas.blade.php
	@extends('app')

@section('htmlheader_title')
    Mis Apuestas
@endsection

@section('contentheader_title')
    Mis Apuestas
@endsection

@section('contentheader_description')
    Todas Mis Apuestas.
@endsection

@section('nivelApu')
    Mis Apuestas
@endsection

@section('main-content')
		<div class="row">
		
			<div class="pad margin no-print hidden" id="divMensaje">
		      	<div class="alert alert-success alert-dismissible" id="divAlert">
		        	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
		        	<b><i class="icon fa fa-check"></i> Alerta!</b>
		        	<i id='mensaje'></i>
		  		</div>
		    </div>

			<div class="col-md-10 col-lg-offset-1">
				
				<div class="box box-solid box-info" id="panel_apostadores">
					<div class="box-header">
		              	<h3 class="box-title">Mis Apustas</h3>
		            </div>
					<div class="box-body">
						<div class="col-lg-12">
							<div class="box-body table-responsive no-padding">
								<table class="table table-hover" id="tabla_apostadores">
									<thead>
										<tr>
											<th>Nombre de la Apuesta:</th>
											<th>Valor</th>
											<th>Tipo De Apuesta</th>
											<th>Primer Aversario</th>
											<th>Primer Aversario</th>
											<th>Fecha de Terminacion</th>
											<th>Ver</th>
											<th>Eliminar</th>
											<th>Compartir</th>
										</tr>
									</thead>
									<tbody>
										 @foreach ($apuestas as $apuesta)

											<tr id='{{ $apuesta->id }}'>
												<td>{{ $apuesta->nombre_apuesta }}</td>
												<td  align="right">${{ $apuesta->valor_apuesta }}</td>
												<td>{{ $apuesta->tipo_apuesta }}</td>
												<td>{{ $apuesta->aversario1_apuesta }}</td>
												<td>{{ $apuesta->aversario2_apuesta }}</td>
												<td align="center">{{ $apuesta->fin_apuesta }}</td>
												<td align="center">
													
													<a href="{{ route('apuesta.edit',$apuesta->id) }}" class='btn btn-sm btn-social-icon editarApuesta' style='color: #00a65a'><i class='fa  fa-eye'></i></a>
												</td>
												<td class='eliminar_apuesta' data-id='{{ $apuesta->id }}'>
											 		<a class='btn btn-sm btn-social-icon' style='color: #dd4b39'>
											 			<i class='fa  fa-close'></i>
											 		</a>
											 	</td>
												<td align="center">
													
													<a href="{{ route('apostadores.show',$apuesta->id) }}" class='btn btn-sm btn-social-icon editarApuesta' style='color: #337ab7'><i class='fa fa-facebook'></i></a>
												</td>
											</tr>
										@endforeach
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>

		<!-- token -->
		<meta name="_token" content="{!! csrf_token() !!}" />

		<script type="text/javascript">
			$(document).ready(function() {
				function eliminarApuesta(){
			    	var formData = {
						id: $(this).data('id')
			        }

			        $.ajax({
						type: 'DELETE',
			            headers: {
			                'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
			            },
			            url: '/apuesta/'+formData.id,
			            dataType: 'json',
			            success: function(data){
			            	console.log(data);
			            	$("#"+formData.id).remove();

			            	$("#divAlert").removeClass('alert-success');
			            	$("#divAlert").addClass('alert-danger');
			               	$("#divMensaje").removeClass('hidden');
			               	$("#divMensaje").removeClass('animated pulse');
			               	$("#divMensaje").addClass('animated pulse');
			               	$("#mensaje").text('Se ha Eliminado Su Apuesta.');
			            	
			            },
			            error: function(data){
			            	console.log('Error Eliminar');
			            }
					});

			    }

	    		$(".eliminar_apuesta").click(eliminarApuesta);
			});
		</script>
@endsection